// Video
export const VIDEO_CODEC = "avc";
export const VIDEO_CODEC_STRING = "avc1.42001f"; // H.264 Baseline Level 3.1
export const VIDEO_WIDTH = 640;
export const VIDEO_HEIGHT = 480;
export const VIDEO_FRAMERATE = 30;
export const VIDEO_BITRATE = 1_000_000;
export const KEYFRAME_INTERVAL = 2; // seconds

// Audio
export const AUDIO_CODEC = "opus";
export const AUDIO_CODEC_STRING = "Opus"; // Opus in CMAF/ISOBMFF
export const AUDIO_SAMPLERATE = 48000;
export const AUDIO_CHANNELS = 1;
export const AUDIO_BITRATE = 64_000;

// Static moov boxes (Base64)
// Generated from mediabunny with the above codec settings.
// The creation_time/modification_time fields in mvhd/tkhd/mdhd vary per run,
// but MSE ignores them — playback timing comes from moof/tfdt in each fragment.
export const VIDEO_MOOV_BASE64 =
	"AAACk21vb3YAAABsbXZoZAAAAADlz+PA5c/jwAAAA+gAAAAAAAEAAAEAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAH3dHJhawAAAFx0a2hkAAAAA+XP48Dlz+PAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAQAAAAAKAAAAB4AAAAAABk21kaWEAAAAgbWRoZAAAAADlz+PA5c/jwAAA4QAAAAAAVcQAAAAAADdoZGxyAAAAAG1obHJ2aWRlAAAAAAAAAAAAAAAATWVkaWFidW5ueVZpZGVvSGFuZGxlcgAAAAE0bWluZgAAABR2bWhkAAAAAQAAAAAAAAAAAAAAJGRpbmYAAAAcZHJlZgAAAAAAAAABAAAADHVybCAAAAABAAAA9HN0YmwAAACoc3RzZAAAAAAAAAABAAAAmGF2YzEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAACgAHgAEgAAABIAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY//8AAAAvYXZjQwFkAB7/4QAUJ2QAHqwTFHAoD2moCAg1sPCAQngBAAQo7jyw/fj4AAAAABNjb2xybmNseAABAAEABgAAAAAQc3R0cwAAAAAAAAAAAAAAEHN0c2MAAAAAAAAAAAAAABRzdHN6AAAAAAAAAAAAAAAAAAAAEHN0Y28AAAAAAAAAAAAAAChtdmV4AAAAIHRyZXgAAAAAAAAAAQAAAAEAAAAAAAAAAAAAAAA=";

export const AUDIO_MOOV_BASE64 =
	"AAACLm1vb3YAAABsbXZoZAAAAADlz+PA5c/jwAAAA+gAAAAAAAEAAAEAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAGSdHJhawAAAFx0a2hkAAAAA+XP48Dlz+PAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAABAQAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAABLm1kaWEAAAAgbWRoZAAAAADlz+PA5c/jwAAAu4AAAAAAVcQAAAAAADdoZGxyAAAAAG1obHJzb3VuAAAAAAAAAAAAAAAATWVkaWFidW5ueVNvdW5kSGFuZGxlcgAAAADPbWluZgAAABBzbWhkAAAAAAAAAAAAAAAkZGluZgAAABxkcmVmAAAAAAAAAAEAAAAMdXJsIAAAAAEAAACTc3RibAAAAEdzdHNkAAAAAAAAAAEAAAA3T3B1cwAAAAAAAAABAAAAAAAAAAAAAQAQAAAAALuAAAAAAAATZE9wcwABATgAALuAAAAAAAAAEHN0dHMAAAAAAAAAAAAAABBzdHNjAAAAAAAAAAAAAAAUc3RzegAAAAAAAAAAAAAAAAAAABBzdGNvAAAAAAAAAAAAAAAobXZleAAAACB0cmV4AAAAAAAAAAEAAAABAAAAAAAAAAAAAAAA";

// Build catalog JSON
export function buildCatalog(namespace: string) {
	return {
		version: 1,
		tracks: [
			{
				namespace,
				name: "video",
				packaging: "cmaf",
				mimeType: "video/mp4",
				codec: VIDEO_CODEC_STRING,
				initData: VIDEO_MOOV_BASE64,
				timescale: 90000,
				isLive: true,
				width: VIDEO_WIDTH,
				height: VIDEO_HEIGHT,
				framerate: VIDEO_FRAMERATE,
				bitrate: VIDEO_BITRATE,
			},
			{
				namespace,
				name: "audio",
				packaging: "cmaf",
				mimeType: "audio/mp4",
				codec: AUDIO_CODEC_STRING,
				initData: AUDIO_MOOV_BASE64,
				timescale: AUDIO_SAMPLERATE,
				isLive: true,
				samplerate: AUDIO_SAMPLERATE,
				channelConfig: String(AUDIO_CHANNELS),
				bitrate: AUDIO_BITRATE,
			},
		],
	};
}

// Default namespace with timestamp suffix
export function defaultNamespace(): string {
	const now = new Date();
	const ts = `${now.getHours()}${String(now.getMinutes()).padStart(2, "0")}`;
	return `msf/demo-${ts}`;
}
