use tracing::Span;

use crate::modules::{
    domain::session_id::SessionId, session::moqt_session_event::MoqtSessionEvent,
};

pub(super) fn session_event_span(
    session_id: SessionId,
    session_span: &Span,
    event: &MoqtSessionEvent,
) -> Span {
    match event {
        MoqtSessionEvent::PublishNamespace(handler) => tracing::info_span!(
            parent: session_span,
            "relay.session.event",
            session_id = %session_id,
            event = "PublishNamespace",
            track_namespace = %handler.track_namespace(),
        ),
        MoqtSessionEvent::PublishNamespaceDone(handler) => tracing::info_span!(
            parent: session_span,
            "relay.session.event",
            session_id = %session_id,
            event = "PublishNamespaceDone",
            track_namespace = %handler.track_namespace(),
        ),
        MoqtSessionEvent::SubscribeNamespace(handler) => tracing::info_span!(
            parent: session_span,
            "relay.session.event",
            session_id = %session_id,
            event = "SubscribeNamespace",
            track_namespace_prefix = %handler.track_namespace_prefix(),
        ),
        MoqtSessionEvent::UnsubscribeNamespace(handler) => tracing::info_span!(
            parent: session_span,
            "relay.session.event",
            session_id = %session_id,
            event = "UnsubscribeNamespace",
            track_namespace_prefix = %handler.track_namespace_prefix(),
        ),
        MoqtSessionEvent::Publish(handler) => tracing::info_span!(
            parent: session_span,
            "relay.session.event",
            session_id = %session_id,
            event = "Publish",
            track_namespace = %handler.track_namespace(),
            track_name = %handler.track_name(),
            track_alias = handler.track_alias(),
            group_order = ?handler._group_order(),
            content_exists = ?handler._content_exists(),
            forward = handler._forward(),
            delivery_timeout = ?handler._delivery_timeout(),
            max_cache_duration = ?handler._max_cache_duration(),
        ),
        MoqtSessionEvent::Subscribe(handler) => tracing::info_span!(
            parent: session_span,
            "relay.session.event",
            session_id = %session_id,
            event = "Subscribe",
            subscribe_id = handler.subscribe_id(),
            track_namespace = %handler.track_namespace(),
            track_name = %handler.track_name(),
            subscriber_priority = handler._subscriber_priority(),
            group_order = ?handler._group_order(),
            forward = handler._forward(),
            filter_type = ?handler._filter_type(),
            max_cache_duration = ?handler._max_cache_duration(),
            delivery_timeout = ?handler._delivery_timeout(),
        ),
        MoqtSessionEvent::Unsubscribe(handler) => tracing::info_span!(
            parent: session_span,
            "relay.session.event",
            session_id = %session_id,
            event = "Unsubscribe",
            subscribe_id = handler.subscribe_id(),
        ),
        MoqtSessionEvent::Disconnected() => tracing::info_span!(
            parent: session_span,
            "relay.session.event",
            session_id = %session_id,
            event = "Disconnected",
        ),
        MoqtSessionEvent::Fetch(handler) => tracing::info_span!(
            parent: session_span,
            "relay.session.event",
            session_id = %session_id,
            event = "Fetch",
            request_id = handler.request_id(),
            fetch_params = ?handler.fetch_params(),
        ),
        MoqtSessionEvent::ProtocolViolation() => tracing::info_span!(
            parent: session_span,
            "relay.session.event",
            session_id = %session_id,
            event = "ProtocolViolation",
        ),
        MoqtSessionEvent::GoAway(handler) => tracing::info_span!(
            parent: session_span,
            "relay.session.event",
            session_id = %session_id,
            event = "GoAway",
            new_session_uri = %handler.new_session_uri(),
        ),
        MoqtSessionEvent::MaxRequestId(handler) => tracing::info_span!(
            parent: session_span,
            "relay.session.event",
            session_id = %session_id,
            event = "MaxRequestId",
            request_id = handler.request_id(),
        ),
        MoqtSessionEvent::RequestsBlocked(handler) => tracing::info_span!(
            parent: session_span,
            "relay.session.event",
            session_id = %session_id,
            event = "RequestsBlocked",
            maximum_request_id = handler.maximum_request_id(),
        ),
        MoqtSessionEvent::PublishNamespaceCancel(handler) => tracing::info_span!(
            parent: session_span,
            "relay.session.event",
            session_id = %session_id,
            event = "PublishNamespaceCancel",
            track_namespace = %handler.track_namespace(),
            error_code = handler.error_code(),
            error_reason = %handler.error_reason(),
        ),
        MoqtSessionEvent::PublishDone(handler) => tracing::info_span!(
            parent: session_span,
            "relay.session.event",
            session_id = %session_id,
            event = "PublishDone",
            request_id = handler.request_id(),
            status_code = handler.status_code(),
            stream_count = handler.stream_count(),
            error_reason = %handler.error_reason(),
        ),
        MoqtSessionEvent::SubscribeUpdate(handler) => tracing::info_span!(
            parent: session_span,
            "relay.session.event",
            session_id = %session_id,
            event = "SubscribeUpdate",
            request_id = handler.request_id(),
            subscription_request_id = handler.subscription_request_id(),
            start_location = ?handler.start_location(),
            end_group = handler.end_group(),
            subscriber_priority = handler.subscriber_priority(),
            forward = handler.forward(),
        ),
        MoqtSessionEvent::FetchCancel(handler) => tracing::info_span!(
            parent: session_span,
            "relay.session.event",
            session_id = %session_id,
            event = "FetchCancel",
            request_id = handler.request_id(),
        ),
        MoqtSessionEvent::TrackStatus(handler) => tracing::info_span!(
            parent: session_span,
            "relay.session.event",
            session_id = %session_id,
            event = "TrackStatus",
            request_id = handler.request_id(),
            track_namespace = %handler.track_namespace(),
            track_name = %handler.track_name(),
        ),
    }
}
