#[cfg(not(target_arch = "wasm32"))]
pub(crate) mod client_crypto;
pub(crate) mod connect_target;
#[cfg(not(target_arch = "wasm32"))]
pub(crate) mod crypto_provider;
#[cfg(not(target_arch = "wasm32"))]
pub(crate) mod dual;
#[cfg(not(target_arch = "wasm32"))]
pub(crate) mod quic;
pub(crate) mod read_error;
#[cfg(not(target_arch = "wasm32"))]
pub(crate) mod server_transport_config;
pub(crate) mod transport_connection;
pub(crate) mod transport_connection_creator;
pub(crate) mod transport_receive_stream;
pub(crate) mod transport_send_stream;
pub(crate) mod transport_stats;
#[cfg(not(target_arch = "wasm32"))]
pub(crate) mod webtransport;
