version: 2.1

jobs:
  clippy_check:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run:
          name: Install Rust toolchain and Clippy
          command: |
            rustup component add clippy
      - run:
          name: Run Clippy
          command: |
            cargo clippy -- -D warnings
  unit_test:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: |
            cargo test
  prettier:
    docker:
      - image: cimg/node:21.6.2
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install ./js
      - run:
          name: Check Prettier Formatting
          command: npx prettier --check "js/**/*.{js,jsx,ts,tsx,json,css,md}"

workflows:
  version: 2
  build_and_test:
    jobs:
      - clippy_check:
          filters:
            branches:
              ignore: /main|master/
      - unit_test:
          filters:
            branches:
              ignore: /main|master/
      - prettier:
          filters:
            branches:
              ignore: /main|master/
