from typing import AsyncIterator, Optional, Union

async def connect(url: str, *, insecure: bool = False) -> Session:
    """Connect to a MoQT peer.

    The URL scheme selects the transport: ``moqt://host[:port]`` for raw QUIC
    (default port 4433) and ``https://host[:port][/path]`` for WebTransport
    (default port 443).
    """

def listen(
    port: int, cert_path: str, key_path: str, *, keep_alive_interval_sec: int = 5
) -> Server:
    """Listen for both raw QUIC and WebTransport clients on one UDP port."""

class Server:
    async def accept(self) -> Session: ...
    def __aiter__(self) -> AsyncIterator[Session]: ...
    async def __anext__(self) -> Session: ...

Event = Union[
    "SubscribeRequest",
    "PublishRequest",
    "PublishNamespaceRequest",
    "SubscribeNamespaceRequest",
    "Disconnected",
    "ProtocolViolation",
]

class Session:
    async def subscribe(self, namespace: str, name: str) -> TrackReader: ...
    async def publish(
        self, namespace: str, name: str, *, first_group_id: Optional[int] = None
    ) -> TrackWriter: ...
    async def publish_namespace(self, namespace: str) -> None: ...
    async def subscribe_namespace(self, prefix: str) -> None: ...
    async def next_event(self) -> Optional[Event]: ...
    def __aiter__(self) -> AsyncIterator[Event]: ...
    async def __anext__(self) -> Event: ...
    def close(self, reason: str = "") -> None: ...

class SubscribeRequest:
    namespace: str
    name: str
    async def accept(self, *, first_group_id: Optional[int] = None) -> TrackWriter: ...
    async def reject(self, code: int, reason: str) -> None: ...

class PublishRequest:
    namespace: str
    name: str
    async def accept(self) -> TrackReader: ...
    async def reject(self, code: int, reason: str) -> None: ...

class PublishNamespaceRequest:
    namespace: str
    async def accept(self) -> None: ...
    async def reject(self, code: int, reason: str) -> None: ...

class SubscribeNamespaceRequest:
    prefix: str
    async def accept(self) -> None: ...
    async def reject(self, code: int, reason: str) -> None: ...

class Disconnected: ...
class ProtocolViolation: ...

class MoqObject:
    group_id: int
    object_id: int
    payload: bytes
    immutable_extensions: list[bytes]

class TrackReader:
    async def next_object(self) -> Optional[MoqObject]: ...
    def __aiter__(self) -> AsyncIterator[MoqObject]: ...
    async def __anext__(self) -> MoqObject: ...

class TrackWriter:
    async def start_group(self, group_id: Optional[int] = None) -> None: ...
    async def write(self, payload: bytes, *, immutable_extensions: list[bytes] = ...) -> None: ...
    async def write_group(self, payload: bytes, group_id: Optional[int] = None) -> None: ...
    async def finish(self) -> None: ...
    async def groups(self) -> int: ...
