[package]
name = "server-sdk"
version = "0.1.0"
edition = "2024"

[dependencies]
moqt = {path = "../../moqt"}
tokio = { version = "1.45.0", features = ["full", "tracing"] }
tracing = "0.1.37"
async-trait = "0.1.74"
anyhow = { version = "1.0.75", features = ["backtrace"] }