[package]
name = "publisher"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
base64 = "0.22"
bytes = "1"
msf = { path = "../msf" }
mediapack = { path = "../mediapack", features = ["moqt"] }
moqt = { path = "../moqt" }
serde_json = "1.0"
tokio = { version = "1", features = ["rt", "sync", "time"] }
tracing = "0.1"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt", "test-util"] }
