name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # mainブランチにpushされたときに実行

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Install wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      # 3. wasm-pack build（例：rust/ に Rust クレートがある場合）
      - name: Build wasm with wasm-pack
        run: wasm-pack build --target web
        working-directory: rust

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: js

      - name: Build with Vite
        run: npm run build
        working-directory: js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: js/dist
